name: pytest
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: poetry install --no-interaction
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v2.5.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Action Failed
          body: ${{ github.repository }} failed on ${{ github.sha }}
          to: leonard.papenmeier@gmail.com