
seed: 42
defaults:
  - model: singletask_lognormal
  - acq_opt: sample_best_max_100
  - algorithm: colabo_logei
  - benchmark: hartmann4
  - prior: default
  - prior_value: null

experiment_group: test
experiment_name: ${benchmark.name}_${algorithm.name}_run_${seed}
result_path: ./../../../results/${experiment_group}/${benchmark.name}/${algorithm.name}
q: 1
